server:
  port: 9200

security:
  jwt:
    public-key: classpath:public.txt

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.16.60.8;databaseName=Intranet2
    username: sa
    password: Adr@2!0&@
    hikari:
      register-mbeans: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  email:
    subject: Azerbaycan Dovlet Reklam Agentliyi
    body: Shifreni deyishmek ucun linke daxil olun http://localhost:4200/sigin/forgetpassword/changepassword?token=%s
  app-name: RESERVATION


file:
  upload:
    path:
      win: C:\\uploads