server:
  port: 9200

security:
  jwt:
    public-key: classpath:public.txt

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.16.60.8;databaseName=Intranet2
    username: sa
    password: Adr@2!0&@
    hikari:
      register-mbeans: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: intranet.adra1@gmail.com
    password: adra@adra
    subject: Azərbaycan Dövlət Reklam Agentliyi (Reservasiya bildirişi)
  app-name: RESERVATION


file:
  upload:
    path:
      win: C:\\uploads